In [2]:
import pandas as pd
import numpy as np

# DataFrame 的计算
# ---------------------------------------------------------------------
# 不同索引，返回结果的索引是索引的并集(补NaN)
# Series
s1 = pd.Series([7.3,-2.5,3.4,1.5],index=['a','c','d','e'])
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])

In [3]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [4]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [5]:
s1 + s2  # 对应索引做相应计算，不同索引值为NaN

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [6]:
# DataFrame

df1 = pd.DataFrame(np.arange(9.).reshape(3,3),
                   index=['Ohio','Texas','Colorado'],
                   columns=list('bcd'))
df2 = pd.DataFrame(np.arange(12).reshape(4,3),
                   index=['Utah','Ohio','Texas','Oregon'],
                   columns=list('bde'))


In [7]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [8]:
df2

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [9]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [25]:
# 使用填充值的计算
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),
                   columns=list('abcde'))

In [26]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [27]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [28]:
df2.loc[1,'b'] = np.nan
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [29]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [30]:
df1.add(df2, fill_value=0)  # fill_value将不同的索引补零后在做计算

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [31]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [32]:
df1.rdiv(1)  # r取倒数，除以1再取倒数

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [4]:
# --------------------------------------------------------------
# DataFrame 和 Series 之间的运算(类似不同维度数组间的操作)
arr = np.arange(12.).reshape((3, 4))  # 二维数组
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [5]:
arr[0]  # 一维数组

array([0., 1., 2., 3.])

In [6]:
arr - arr[0]  # 不同维度数组之间的计算：对每行都进行了操作(广播机制)

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [7]:
frame = pd.DataFrame(np.arange(12.).reshape(4,3),
                     index=['Utah','Ohio','Texas','Oregon'],
                     columns=list('bde'))
series = frame.iloc[0]  # 整数索引

In [8]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [9]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [10]:
frame - series  # 默认列匹配，行广播

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [16]:
series2 = pd.Series(np.arange(3),index=['b','e','f'])
series2

b    0
e    1
f    2
dtype: int32

In [17]:
frame + series2  # s索引不在DataFrame中，会重建索引形成联合(补NaN)

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [18]:
# 修改为行匹配，列广播
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [19]:
# 使用算术方法
frame.sub(series3,axis=0)  # axis定义匹配轴，axis=0意味着行匹配，列广播

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [20]:
# ----------------------------------------------------------------
# 函数应用和映射
# NumPy的通用函数对pandas对象也有效
frame = pd.DataFrame(np.random.randn(4,3),
                     index=['Utah','Ohio','Texas','Oregon'],
                     columns=list('bde'))
frame

b         d         e
Utah   -0.096939 -0.153467 -0.502939
Ohio   -0.089278  0.377866 -1.109134
Texas  -0.138653 -0.380553  1.550077
Oregon  0.224252  0.121079  0.569062

In [21]:
np.abs(frame)  # 使用NumPy的函数对pandas对象逐元素操作

b         d         e
Utah    0.096939  0.153467  0.502939
Ohio    0.089278  0.377866  1.109134
Texas   0.138653  0.380553  1.550077
Oregon  0.224252  0.121079  0.569062

In [23]:
# 调用apply方法，以自定义函数为参数对行或列进行相应的操作
f = lambda x: x.max() - x.min()
frame.apply(f,axis=0)  # 设置行匹配，列广播

b    0.362904
d    0.758419
e    2.659211
dtype: float64

In [24]:
frame.apply(f,axis=1)

Utah      0.406000
Ohio      1.487000
Texas     1.930630
Oregon    0.447983
dtype: float64

In [25]:
# 自定义函数也可以返回一个Series
def f(x):
    """返回数组最大值和最小值形成的Series"""

    return pd.Series([x.min(), x.max()], index=['min','max'])

frame.apply(f,axis=0)

b         d         e
min -0.138653 -0.380553 -1.109134
max  0.224252  0.377866  1.550077

In [26]:
# applymap方法对每个元素进行操作,返回一个新对象
data_format = lambda x: '%.2f' % x
frame.applymap(data_format)

b      d      e
Utah    -0.10  -0.15  -0.50
Ohio    -0.09   0.38  -1.11
Texas   -0.14  -0.38   1.55
Oregon   0.22   0.12   0.57

In [27]:
frame.loc['Utah']

b   -0.096939
d   -0.153467
e   -0.502939
Name: Utah, dtype: float64

In [28]:
# ----------------------------------------------------------------------
# 排序
# sort_index方法按行或列索引进行排序，返回一个新对象
obj = pd.Series(np.arange(4), index=['d','a','b','c'])  # Series排序
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int32

In [29]:
frame = pd.DataFrame(np.arange(8).reshape(2,4),
                     index=['three','one'],
                     columns=['d','a','b','c'])  # DataFrame排序
frame.sort_index()  # 默认按行索引排序

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [30]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [31]:
frame.sort_index(ascending=False)  # 降序排列

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [32]:
frame.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [33]:
# sort_value方法按元素数值进行排序，返回一个新对象
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [34]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])  # 缺失值NaN会排至尾部
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [35]:
# DataFrame可以使用一列或多列的值进行排序:可选参数by
frame = pd.DataFrame({
    'b': [4, 7, -3, 2],
    'a': [0, 1, 0, 1]
})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [36]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [37]:
# -------------------------------------------------------------------
# 排名
# rank方法对Series和DataFrame实现排名
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()  # 将平均排名分配到每个组来打破平级关系

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [38]:
# 可选参数method可按照不同方式进行排名
obj.rank(method='first')  # first按照值在数据中出现的次序进行排名

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [39]:
# 降序排名
obj.rank(ascending=False, method='max') # max使用最大排名

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [40]:
frame = pd.DataFrame({
    'b': [4.3, 7, -3, 2],
    'a': [0, 1, 0, 1],
    'c': [-2, 5, 8, -2.5]
})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [41]:
frame.rank(axis=0)  # 行匹配，列广播

b    a    c
0  3.0  1.5  2.0
1  4.0  3.5  3.0
2  1.0  1.5  4.0
3  2.0  3.5  1.0

In [42]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0