In [1]:
import numpy as np

# --------------------------------------------
# 一维数组
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
arr[5]  # 索引

5

In [3]:
arr[5:8]  # 切片

array([5, 6, 7])

In [4]:
arr[5:8] = 12
arr  # 与list不同，切片是原数组的视图，任何对于视图的修改都会反映到原数组上

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [5]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [6]:
arr_slice[1] = 12345  # 改变arr_slice 也会改变原数组
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [7]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [8]:
# 复制数组切片而不是获取一份视图，需显示地复制数组切片
arr[5:8].copy()

array([64, 64, 64])

In [10]:
arr_slice2 = arr[5:8].copy()
arr_slice2[:] = 32
print(arr_slice2)
print(arr)  # 显示复制之后再修改切片，不会修改原数组

[32 32 32]
[ 0  1  2  3  4 64 64 64  8  9]


In [12]:
# ------------------------------------------------
# 二维数组
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_2d


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr_2d[2]  # 一维数组索引

array([7, 8, 9])

In [14]:
arr_2d[2][2]  # 单个元素索引

9

In [16]:
arr_2d[2, 2]

9

In [25]:
# 维度上两个冒号，按照原数组的维度进行切片
arr_2d[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr_2d[:, :1]

array([[1],
       [4],
       [7]])

In [27]:
# 索引与切片混合，获得低纬度的切片(降低一个维度，注意两者的区别)
arr_2d[:, 0]

array([1, 4, 7])

In [28]:
# 对切片进行赋值，同样地会改变原数组的值
arr_2d[:,:1] = 3
arr_2d

array([[3, 2, 3],
       [3, 5, 6],
       [3, 8, 9]])

In [29]:
arr_2d[:, 1] = 6
arr_2d

array([[3, 6, 3],
       [3, 6, 6],
       [3, 6, 9]])

In [30]:
# -----------------------------------------------------------
# 更高维数组(以2*2*3三维数组为例)
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr_3d
# 索引
arr_3d[0]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [32]:
arr_3d[0, 1]

array([4, 5, 6])

In [33]:
arr_3d[0, 1, 2]

6

In [35]:
# 切片
arr_3d[0, :, :2]


array([[1, 2],
       [4, 5]])

In [36]:
arr_3d[0, 0, :2]

array([1, 2])

In [37]:
arr_3d[:1, :, :1]

array([[[1],
        [4]]])

In [38]:
# 对切片赋值，同样会改变原数组的值
arr_3d[0, :, 0] = 0
arr_3d

array([[[ 0,  2,  3],
        [ 0,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [40]:
# 布尔索引（布尔数组的长度必须与数组轴索引长度一致）

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [41]:
data

array([[-0.02489957, -0.19096735,  1.11003824, -1.51453455],
       [-1.68687043, -0.1610275 , -2.06750869, -0.82923164],
       [ 2.07326572,  0.34564121, -0.53589748, -1.61476564],
       [ 1.33742135,  0.95615585,  2.24106503,  0.18693755],
       [-0.14682596,  0.60705322,  0.94424759, -0.36181923],
       [-0.16770241,  1.32237133,  2.10025598, -1.21025615],
       [ 0.2058972 , -0.1098019 , -0.15409755,  0.73292219]])

In [42]:
names == 'Bob'  # 返回布尔数组


array([ True, False, False,  True, False, False, False])

In [43]:
data[names == 'Bob']  # 布尔索引

array([[-0.02489957, -0.19096735,  1.11003824, -1.51453455],
       [ 1.33742135,  0.95615585,  2.24106503,  0.18693755]])

In [46]:
numbers = np.array([1, 3, 5, 7])
numbers

array([1, 3, 5, 7])

In [47]:
data[:,numbers == 1]

array([[-0.02489957],
       [-1.68687043],
       [ 2.07326572],
       [ 1.33742135],
       [-0.14682596],
       [-0.16770241],
       [ 0.2058972 ]])

In [48]:
data[names == 'Bob', :]


array([[-0.02489957, -0.19096735,  1.11003824, -1.51453455],
       [ 1.33742135,  0.95615585,  2.24106503,  0.18693755]])

In [49]:
data[names != 'Bob', :]


array([[-1.68687043, -0.1610275 , -2.06750869, -0.82923164],
       [ 2.07326572,  0.34564121, -0.53589748, -1.61476564],
       [-0.14682596,  0.60705322,  0.94424759, -0.36181923],
       [-0.16770241,  1.32237133,  2.10025598, -1.21025615],
       [ 0.2058972 , -0.1098019 , -0.15409755,  0.73292219]])

In [51]:
# 布尔算术运算符（‘&’，‘|’），关键字and、or对布尔值数组无效
mask = (names == 'Bob') | (names == 'Will')
data[mask, :]


array([[-0.02489957, -0.19096735,  1.11003824, -1.51453455],
       [ 2.07326572,  0.34564121, -0.53589748, -1.61476564],
       [ 1.33742135,  0.95615585,  2.24106503,  0.18693755],
       [-0.14682596,  0.60705322,  0.94424759, -0.36181923]])

In [52]:
data < 0

array([[ True,  True, False,  True],
       [ True,  True,  True,  True],
       [False, False,  True,  True],
       [False, False, False, False],
       [ True, False, False,  True],
       [ True, False, False,  True],
       [False,  True,  True, False]])

In [53]:
# 对每个元素：负值置0
data[data < 0] = 0
data

array([[0.        , 0.        , 1.11003824, 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [2.07326572, 0.34564121, 0.        , 0.        ],
       [1.33742135, 0.95615585, 2.24106503, 0.18693755],
       [0.        , 0.60705322, 0.94424759, 0.        ],
       [0.        , 1.32237133, 2.10025598, 0.        ],
       [0.2058972 , 0.        , 0.        , 0.73292219]])

In [54]:
# 对每行或每列设置数值
data[names != 'Joe',:] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 1.32237133, 2.10025598, 0.        ],
       [0.2058972 , 0.        , 0.        , 0.73292219]])

In [55]:
data[:, numbers == 3] = 1
data

array([[7.        , 1.        , 7.        , 7.        ],
       [0.        , 1.        , 0.        , 0.        ],
       [7.        , 1.        , 7.        , 7.        ],
       [7.        , 1.        , 7.        , 7.        ],
       [7.        , 1.        , 7.        , 7.        ],
       [0.        , 1.        , 2.10025598, 0.        ],
       [0.2058972 , 1.        , 0.        , 0.73292219]])

In [56]:
# 神奇索引：用整数数组进行索引
arr_index = np.empty((8, 4))
arr_index

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [57]:
for i in range(8):
    arr_index[i,:] = i
arr_index

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [58]:
arr_index[[1, 3, 5, 7]]  # 用整数数组进行索引

array([[1., 1., 1., 1.],
       [3., 3., 3., 3.],
       [5., 5., 5., 5.],
       [7., 7., 7., 7.]])

In [59]:
arr_index[[-1, -2, -3]]  # 用负数从尾部进行索引

array([[7., 7., 7., 7.],
       [6., 6., 6., 6.],
       [5., 5., 5., 5.]])

In [60]:
arr_2 = np.arange(32).reshape((8, 4))
arr_2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [62]:
# 使用多个数组进行索引，根据对应元素选出一个一维数组
arr_2[[1, 5, 7, 2], [0, 3, 1, 2]]


array([ 4, 23, 29, 10])

In [63]:
arr_2[[-1]] = 0
arr_2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [ 0,  0,  0,  0]])

In [64]:
arr_2[[1, 5, 7, 2], [0, 3, 1, 2]] = 1
arr_2

array([[ 0,  1,  2,  3],
       [ 1,  5,  6,  7],
       [ 8,  9,  1, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  1],
       [24, 25, 26, 27],
       [ 0,  1,  0,  0]])