In [2]:
# 合并数组
import numpy as np
a = np.array([1,1,1])
b = np.array([2,2,2])
np.vstack((a, b))  # 竖直合并


array([[1, 1, 1],
       [2, 2, 2]])

In [3]:
c = np.vstack((a, b))
print(a.shape)
print(c.shape)


(3,)
(2, 3)


In [4]:
d = np.hstack((a, b))  # 水平合并
print(b.shape)
print(d.shape)

(3,)
(6,)


In [5]:
d

array([1, 1, 1, 2, 2, 2])

In [10]:
# 一维数组T方法转置后形状不会发生改变，仍是一维数组，这点与Matlab不同
print(a.shape)
print(a.T.shape)

(3,)
(3,)


In [11]:
# 因此一维数组转置要用reshape方法，且生成的是二维数组
a_transfer = a.reshape((3,1))
a_transfer

array([[1],
       [1],
       [1]])

In [8]:
# ----------------------------------------------------------------------
# 多个一维数组合并
e_0 = np.concatenate((a,b,b,a),axis=0)  # 横向合并
e_0


array([1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1])

In [13]:
# 多个二维数组合并（注意：a_transfer是二维数组）
f_1 = np.concatenate((a_transfer,a_transfer), axis=1)
f_1

array([[1, 1],
       [1, 1],
       [1, 1]])

In [14]:
f_0 = np.concatenate((a_transfer,a_transfer),axis=0)
f_0

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [15]:
# -----------------------------------------------------------------------
# 矩阵分解
A = np.arange(12).reshape((3,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
# 相等分割
np.split(A,2,axis=1)  # 纵向分割

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [17]:
np.split(A,3,axis=0)  # 横向分割

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [19]:
np.vsplit(A,3)  # 纵向分割

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [20]:
np.hsplit(A,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [18]:
# 不等分割
np.array_split(A,2,axis=0)  # array_split:不等分割；且默认分割后的第一个数组最大

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]])]