In [2]:
# 通用函数
import numpy as np

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# -------------------------------------------------------------
# 一元通用函数
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [5]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [6]:
# -------------------------------------------------------------
# 二元通用函数
x = np.random.randn(8)
y = np.random.randn(8)

x


array([-0.68498421,  0.72581735, -1.51572069, -0.15426598, -0.59882785,
        0.74419246, -0.97037348, -2.09254444])

In [7]:
y

array([ 2.67334583, -1.20202345,  0.01184311,  1.07360768, -0.42117277,
       -0.26982151,  0.96943916,  0.08441916])

In [8]:
np.add(x, y)

array([ 1.98836162e+00, -4.76206094e-01, -1.50387758e+00,  9.19341700e-01,
       -1.02000062e+00,  4.74370947e-01, -9.34318918e-04, -2.00812528e+00])

In [9]:
np.maximum(x, y)

array([ 2.67334583,  0.72581735,  0.01184311,  1.07360768, -0.42117277,
        0.74419246,  0.96943916,  0.08441916])

In [10]:
# 返回多个数组的通用函数
np.modf(x)

(array([-0.68498421,  0.72581735, -0.51572069, -0.15426598, -0.59882785,
         0.74419246, -0.97037348, -0.09254444]),
 array([-0.,  0., -1., -0., -0.,  0., -0., -2.]))

In [11]:
remainder, whole_part = np.modf(y)
remainder

array([ 0.67334583, -0.20202345,  0.01184311,  0.07360768, -0.42117277,
       -0.26982151,  0.96943916,  0.08441916])

In [12]:
whole_part

array([ 2., -1.,  0.,  1., -0., -0.,  0.,  0.])