In [2]:
import numpy as np

# 生成随机数组
data1 = np.random.randn(2, 3)
data2 = np.random.randn(2, 3)
print(data1)
print(data2)

[[-0.31243519 -0.8541427   0.22475491]
 [-0.70091172  0.95283557  0.20774773]]
[[-0.99132535 -2.95773128  0.02947138]
 [-0.66970155 -0.13990859  2.0188958 ]]


In [22]:
# ---------------------------------------------------
# 加减乘除
# 等尺寸数组
data_add = data1 + data2
print(data_add)
data_sub = data1 - data2
print(data_sub)
data_mul = data1 * 10
print(data_mul)
data_div = data2 / 10
print(data_div)

[[-1.30376055 -3.81187398  0.25422629]
 [-1.37061327  0.81292699  2.22664353]]
[[ 0.67889016  2.10358857  0.19528353]
 [-0.03121017  1.09274416 -1.81114807]]
[[-3.12435193 -8.54142704  2.24754909]
 [-7.00911722  9.52835575  2.0774773 ]]
[[-0.09913254 -0.29577313  0.00294714]
 [-0.06697015 -0.01399086  0.20188958]]


array([[-3.20066376, -1.17076455,  4.44929103],
       [-1.42671319,  1.04949902,  4.81353033]])

In [25]:
# 带标量计算:把计算参数传递给每个元素（与matlab相反）
print(1 / data1)
print(1 + data1)
print(1 - data1)
print(2 * data1)

[[-3.20066376 -1.17076455  4.44929103]
 [-1.42671319  1.04949902  4.81353033]]
[[0.68756481 0.1458573  1.22475491]
 [0.29908828 1.95283557 1.20774773]]
[[1.31243519 1.8541427  0.77524509]
 [1.70091172 0.04716443 0.79225227]]
[[-0.62487039 -1.70828541  0.44950982]
 [-1.40182344  1.90567115  0.41549546]]


In [26]:
# 同尺寸数组比较，生成布尔值数组
data2 > data1


array([[False, False, False],
       [ True, False,  True]])

In [7]:
# 生成ndarray
# --------------------------------------------------
# array()函数：接受任意对象生成ndarray数组
numbers_1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(numbers_1)
arr1  # 默认小数的数据类型为float 64（浮点型）

array([6. , 7.5, 8. , 0. , 1. ])

In [8]:
numbers_2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(numbers_2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
# 维度和形状
arr2.ndim  # 维度

2

In [12]:
arr2.shape  # 形状

(2, 4)

In [13]:
arr2.dtype  # 数据类型

dtype('int32')

In [14]:
np.zeros(10)  # 一维数组

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros((3, 6))  # 创建高维数组，zero函数的参数为一个元组

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [17]:
arr3 = np.array([1, 2, 3], dtype=np.float64)  # 指定数据类型
arr3

array([1., 2., 3.])

In [19]:
arr4 = np.array([1, 2, 3], dtype=np.int32)
arr4

array([1, 2, 3])

In [20]:
float_arr4 = arr4.astype(dtype=np.float64)  # 转换数据类型
float_arr4

array([1., 2., 3.])

In [21]:
# --------------------------------------------------------
# arange()函数，内建函数range的数组版
arr5 = np.arange(10)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])