In [1]:
import numpy as np
# 矩阵乘法
# --------------------------------------------------------------
x = np.array([[1., 2., 3.],[4., 5., 6.]])
y = np.array([[6., 23.],[-1, 7],[8, 9]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [2]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [3]:
# 几种矩阵乘法
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [4]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [5]:
x @ y

array([[ 28.,  64.],
       [ 67., 181.]])

In [6]:
# ---------------------------------------------------------------
# 求逆
from numpy.linalg import inv, qr

z = np.random.randn(5, 5)
z

array([[ 2.08287098,  0.85131431, -0.79445956, -0.47935867,  1.62732851],
       [-1.64571918, -0.81841555, -0.37229055,  0.43701311, -0.77286447],
       [-0.23294334, -1.28297412, -0.07503192, -1.74425819,  0.34310377],
       [ 0.01207923,  0.25683118,  0.9628095 ,  0.30062388, -0.3774841 ],
       [ 0.57467838,  0.80269116,  0.38870896,  1.03645348, -1.13455188]])

In [8]:
mat = z.T.dot(z)
mat

array([[ 7.43140688,  3.8833119 , -0.78958024, -0.71207108,  3.92494732],
       [ 3.8833119 ,  3.75083801,  0.28391033,  2.38125653,  0.57005465],
       [-0.78958024,  0.28391033,  1.85349281,  1.04133254, -1.83531604],
       [-0.71207108,  2.38125653,  1.04133254,  4.62781237, -3.00567848],
       [ 3.92494732,  0.57005465, -1.83531604, -3.00567848,  4.79293998]])

In [9]:
inv(mat)  # 求逆

array([[ 21.23555405, -42.73323643,   8.29080732,  29.45637959,
          9.33967609],
       [-42.73323643,  87.60130811, -17.5415623 , -60.915518  ,
        -20.34212897],
       [  8.29080732, -17.5415623 ,   4.56683422,  12.40982867,
          4.82797746],
       [ 29.45637959, -60.915518  ,  12.40982867,  42.89725705,
         14.77626598],
       [  9.33967609, -20.34212897,   4.82797746,  14.77626598,
          6.09478895]])

In [10]:
mat.dot(inv(mat))

array([[ 1.00000000e+00, -3.63957580e-15,  6.12019222e-15,
        -1.70243726e-15, -6.93347419e-15],
       [ 1.87564219e-15,  1.00000000e+00, -6.13692340e-15,
        -7.51808276e-15,  1.60017101e-15],
       [ 4.56026069e-17,  1.57244508e-14,  1.00000000e+00,
        -9.55843316e-15,  4.32397726e-16],
       [ 9.32974643e-15,  3.04234415e-14,  1.49291857e-17,
         1.00000000e+00,  2.24331547e-15],
       [ 9.72656762e-15, -1.37490358e-14,  3.65885239e-15,
         1.73433186e-14,  1.00000000e+00]])

In [11]:
# ----------------------------------------------------------------
# QR分解
q, r = qr(mat)

In [12]:
q

array([[-0.79745668, -0.03858381, -0.22181532,  0.44890348, -0.33445144],
       [-0.41671423, -0.49415492,  0.03055347, -0.22492747,  0.72844649],
       [ 0.08472905, -0.18766431, -0.86571575, -0.42219528, -0.17288865],
       [ 0.07641162, -0.75435991,  0.35000995, -0.15037375, -0.52913435],
       [-0.42118209,  0.38735699,  0.27909448, -0.73961624, -0.21825285]])

In [13]:
r

array([[-9.31888476, -4.69388627,  1.52096338,  1.28333003, -5.77139913],
       [ 0.        , -3.63211767, -1.95412713, -5.99996286,  4.03523073],
       [ 0.        ,  0.        , -1.5685323 ,  0.11011805,  1.02133143],
       [ 0.        ,  0.        ,  0.        ,  0.23224025, -0.68439776],
       [ 0.        ,  0.        ,  0.        ,  0.        , -0.03580975]])