In [1]:
import numpy as np
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
arr.T  # 转置

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [4]:
arr = np.random.randn(6, 3)
arr

array([[-0.01347527, -0.84802588, -1.2451999 ],
       [-0.30429669,  1.43449081,  1.12561275],
       [-1.42778661,  0.05709194,  1.19430899],
       [ 0.80303208,  0.0147116 ,  1.10076473],
       [ 1.94607851,  2.62450327,  0.10824281],
       [-1.29996588,  1.61412716,  4.03141086]])

In [5]:
np.dot(arr.T, arr)  # 矩阵乘法：np.dot

array([[ 8.253346  ,  2.51439452, -6.17705736],
       [ 2.51439452, 12.27381165,  9.54631573],
       [-6.17705736,  9.54631573, 21.71957383]])

In [6]:
np.dot(arr, arr.T)

array([[ 2.26985228, -2.61399775, -1.51632907, -1.39396902, -2.38665459,
        -6.37121663],
       [-2.61399775,  3.41736444,  1.86069804,  1.01577846,  3.29448008,
         7.24883338],
       [-1.51632907,  1.86069804,  3.46820805,  0.16893468, -2.49947147,
         6.76297775],
       [-1.39396902,  1.01577846,  0.16893468,  1.85675993,  1.72052397,
         3.41746696],
       [-2.38665459,  3.29448008, -2.49947147,  1.72052397, 10.68695549,
         2.14281763],
       [-6.37121663,  7.24883338,  6.76297775,  3.41746696,  2.14281763,
        20.54759129]])

In [7]:
# 三维及以上的数组换轴
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [8]:
arr.transpose(1,0,2)

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [9]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [10]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])